### ISSUE TITLE
Add a symbolic link for wlinux-setup

### ISSUE THREAD

**Issue by saigkill** [WhitewaterFoundry/Pengwin#188]
**Is your feature request related to a problem? Please describe.**
After Installation the User learns, he should use 'wlinux-setup' for Setting up WLinux. But this just works for the current Installation instance. After Closing and Running up WLinux a 'wlinux-setup' doesn't work (file not found). But it is available as /etc/setup.

**Describe the solution you'd like**
I propose a sylink: ln -s /etc/setup /usr/bin/wlinux-setup

**Comment by sirredbeard** [comment]
Did you install zsh?

Because if so, we just patched that. #187 

The alias approach seems to be more consistent.

We sometimes do things that there may be a 'more correct' way to do on workstation or server but we are working around WSL.

We will likely revamp how wlinux-setup is located at /etc/setup when we start packaging wlinux-setup as it's own .deb on our own apt repo.

**Comment by saigkill** [comment]
Yes i'm working with zsh. I looked at the patch, and i think that's a good way. Thanks
