### ISSUE TITLE
how to backup wlinux?

### ISSUE THREAD

**Issue by paveldvorak5** [WhitewaterFoundry/Pengwin#367]
What's the proper way to backup and restore wlinux? Something happened to windows andit stopped working. So I would like to have a backup

**Comment by crramirez** [comment]
Hello,

We will release a home backup function soon. For now you can use:

tar -czvf "/mnt/c/Users/**_myuser_**/pengwin_home.tgz" "${HOME}"

This will backup your home directory only. I will leave to other for suggestions about backing up the entire distribution. Windows 19.03 will include this feature.

Regards

**Comment by WSLUser** [comment]
Seeing as wlinux-setup makes it easy to recover the packages you use primarily, I'd make a list of extra packages you use not included with wlinux-setup (that you manually installed, not system defaults) and create a bash script to install these after running wlinux-setup. The same would go for any special configurations you did to your distro instance. Make them executable with chmod and save them to a Windows directory. You should create workspaces in your Windows directories to keep your code from being affected by what happens to the distro. You can always make a copy inside the distro filesystem for faster operations. A side-benefit of this is that you can test your code on multiple distros without having to move any files over (say you want to test your code in Ubuntu after creating it in Wlinux and have Ubuntu installed. You could open up the Ubuntu instance and test your code there without needing to move it.) That also would make those files easily available for Hyper-V VMs and Docker containers.

**Comment by WSLUser** [comment]
A potential action PengWin could do in this regard is include a script in penguin-base that checks what packages are installed on a weekly basis (this includes packages installed via npm, pip, etc.) and automatically create a bash script that saves to the Windows user home directory `(C:/Users/user/BackupInstallScript/backupinstallscript.sh`) or something similar. I see another approach that is a bit more complicated (regards checking the history of commands used, possibly reading the terminal buffer?, and automatically extrapolating the required data when a user terminates the instance). That may be more correct since that would allow configurations (such as configuring 32-bit app compatibility: see my issue) to be saved to the script as well.

**Comment by sirredbeard** [comment]
We are working on a home backup function in pengwin-setup.

We are also looking at a tool to easily backup and restore backups of any WSL distro.

**Comment by Biswa96** [comment]
`wsl.exe` has now `--export` option to backup. You guys may add that with `CreateProcess()`.
