### ISSUE TITLE
WLinux taskbar icon is blank and cannot be removed

### ISSUE THREAD

**Issue by tuetschek** [WhitewaterFoundry/Pengwin#392]
WLinux somehow automatically rebranded to Pengwin on my machine today, which is fine, but there are a few issues with this:

1) There was no notification of this, and the WLinux app seemingly stopped working  – I can find it in the Start Menu, but nothing happens if I try to run it. The Pengwin app appeared as new.
![image](https://user-images.githubusercontent.com/2931158/55835832-25ed5200-5b1d-11e9-8933-ed527c163ac1.png)

2) The pinned WLinux icon on the taskbar disappeared, but still keeps using up space, and there's no obvious way to remove it (the screenshot shows an attempt at right-clicking the "WLinux" entry, after right-clicking the icon). The Pengwin icon seems to be distinct from the WLinux one – I had to pin it again.
![image](https://user-images.githubusercontent.com/2931158/55835773-022a0c00-5b1d-11e9-8969-4617327215bf.png)

2) The window title now says "Unpacking Pengwin", even though there's no "unpacking" going on -- the app seems to work normaly, and my settings and files are preserved. This is not a big problem, but it looks weird.

![image](https://user-images.githubusercontent.com/2931158/55835940-5f25c200-5b1d-11e9-8bbd-488c0d716d6f.png)

My Pengwin version info says 1.2.0.0, my Windows 10 Home is version 1809, build 17763.437.

**Comment by crramirez** [comment]
Hello,

Open the task manager and finish all processes without extension like "init", "dbus", etc. Or restart your PC

Hope it helps

Regards

**Comment by tuetschek** [comment]
Thanks for your reply! Unfortunately restarting didn't change anything :-(.

**Comment by crramirez** [comment]
Ok I am out of ideas. Because any other solution will wipe your pengwin installation. But if you decide to do it, remember to use the home backup feature of pengwin-setup.

You can try clicking the "Repair" button in app settings of pengwin

**Comment by sirredbeard** [comment]
Wow, this sucks. This has gone very wrong for you and I am really sorry.

We have been trying to get the word out about the pending changes via media, our blog, and social media (Twitter, Reddit, etc.) for a couple months. We clearly need to identify more ways to reach our users. Do you have any suggestions?

Second, I want you to know we did everything we could to upgrade everyone in place with backward compatibility so it would be seamless, WLinux would literally become Pengwin overnight. Something has happened with the UWP wrapper on your system, I think the best course of action is to backup your home folder and remove/reinstall Pengwin. I am really sorry to say that because it means we let you down but I think it's the best course of action to get you up and running at this time.

**Comment by bushidocodes** [comment]
I had this issue on my laptop today. I ended up using the bash script linked on the following site to blow away all of the pins in my taskbar and then repin everything:
https://www.tenforums.com/tutorials/3151-reset-clear-taskbar-pinned-apps-windows-10-a.html

**Comment by shadowrylander** [comment]
I'd like to chime in, if possible: I was running WLinux on [`cmder`](https://cmder.net/), using `wlinux -new_console:p`, which is essentially how you would open the console in the command prompt or powershell, and then the cmder command; unfortunately, now it opens up the terminal in a separate `mintty` instance. Is there any way I can open it up in the cmder console again?

**Comment by crramirez** [comment]
Hello,

I don't think we made such change to have now this behavior. To verify, now the command that you are running is: `pengwin -new_console:p` ?

I will try to reproduce it today.

Regards

**Comment by tuetschek** [comment]
@sirredbeard : Thanks for your reply! It's alright – it didn't break anything besides some cosmetic changes, so I'll probably reinstall or just go with @bushidocodes's solution. I was actually aware that the distribution is changing its name (not sure where I read it, I guess some blogs), but I thought I'd have to upgrade manually at some point.

**Comment by shadowrylander** [comment]
@crramirez Thanks! I didn't know how to call it, as sometimes the executable has a different name from the program!

**Comment by crramirez** [comment]
> @crramirez Thanks! I didn't know how to call it, as sometimes the executable has a different name from the program!

You're welcome. Probably you have installed wsltty, and this is the reason why wlinux still worked but in a mintty window.

**Comment by sirredbeard** [comment]
You can also use:

```
Remove-Item "$env:USERPROFILE\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\*" -recurse
Remove-Item -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -recurse 
Get-Process explorer | Stop-Process
```

**Comment by kerbe** [comment]
> Wow, this sucks. This has gone very wrong for you and I am really sorry.

I was apparently lucky, that things didn't go as bad for me. I had been working last night, and at one point I noticed that WLinux icon on taskbar turned black, but things worked OK. While I was sleeping, computer had decided to make reboot. Starting work today, WLinux icons are disappeared, it is found in Start menu search, but button does nothing. Pengwin works, though doesn't have right icon when trying to search. 

> 
> We have been trying to get the word out about the pending changes via media, our blog, and social media (Twitter, Reddit, etc.) for a couple months. We clearly need to identify more ways to reach our users. Do you have any suggestions?

This is indeed million dollar question. I can chime in with these.. Like I didn't know you had a blog. I just took good look at repo's README.md, and didn't find blog mentioned there at all... but it appears to be on your startup website, which is linked there. It just doesn't invite me going there, as there isn't mention that part of information is shared there.
I'm not active Reddit reader (no account, not following any subreddit regularly, diving in there if some Google results take me there). Twitter I occasionally use, but I haven't realised that you are using it. And there it is pretty easy to be lost in sea of tweets.

When I made my first bug report here few weeks back, I noticed re-branding on readme, but there was no further info, anywhere in repo.. made me think that it is something happening in the future, and MS Store would take care of things smoothly.

I started watching releases on repo, hoping to see when things move forward, but I have feeling that currently releases/tags in repo is used a bit unconventional way. Like I don't see anywhere that this 1.2.3.0 is released that I am using, and no idea what state of repo that represents.

How to make it better? Few things I would like to see are roadmap with release schedule. A bit restructuring README.md to make it clear that there is blog and other actively used places where information is shared.
I wouldn't mind if Pengwin had some sort of MOTD when it is opened, something that would pull for example info when new blog post is made. You could then easily snooze it, until next one comes up. A bit similar as Gentoo's eselect news are.
I at least use WSL because I want to have similar feel as with Linux and to use similar tools. I'm not accustomed with real Linux environments to follow outside sources for changes... all information is within Linux and I encounter it on daily usage.

Apologies, as this became quite massive. This just is topic I might be a bit passionate.

**Comment by ste616** [comment]
I just had this same problem, and got quite annoyed because I hadn't realised WLinux was being renamed either. A quick bit of Googling helped me to realise that the issue is that a pin that points to something that gets renamed becomes blank and basically unresponsive.

[https://answers.microsoft.com/en-us/windows/forum/windows_10-start/windows-10-cannot-delete-or-unpin-a-tile-from-the/a90cbc45-fb02-4ba7-bfaa-cd06f53d267f?auth=1&page=3](reference URL)

There is an easy fix though, as I found from [https://techjourney.net/unpin-remove-project-spartan-blank-icon-left-in-windows-10-taskbar/](another page): hold shift as you right click on the blank pin and you'll get a context menu which allows you to unpin.

**Comment by sirredbeard** [comment]
@kerbe Thanks for that feedback. In response I have opened https://github.com/WhitewaterFoundry/Pengwin/issues/404.

@ste616 Sorry for the hassle. Hopefully this is the last time we will be renaming! Thank you for your links. I hope you don't mind I fixed the links in markdown.

**Comment by hltdev8642** [comment]
> I just had this same problem, and got quite annoyed because I hadn't realised WLinux was being renamed either. A quick bit of Googling helped me to realise that the issue is that a pin that points to something that gets renamed becomes blank and basically unresponsive.
> 
> [reference URL](https://answers.microsoft.com/en-us/windows/forum/windows_10-start/windows-10-cannot-delete-or-unpin-a-tile-from-the/a90cbc45-fb02-4ba7-bfaa-cd06f53d267f?auth=1&page=3)
> 
> There is an easy fix though, as I found from [another page](https://techjourney.net/unpin-remove-project-spartan-blank-icon-left-in-windows-10-taskbar/): **hold shift as you right click on the blank pin and you'll get a context menu which allows you to unpin.**

Thank you so much!! I tried so many things and nothing worked who would  have known it was that simple.... Typical windows having features that are left unannounced / explained in an easily visible place / manner - ____ -
