### ISSUE TITLE
alsa unavailable

### ISSUE THREAD

**Issue by cclark2a** [WhitewaterFoundry/Pengwin#418]
Purchased and installed Pengwin to build VCV Rack for compatibility testing.
Followed these instructions for VCV Rack Linux build:
https://vcvrack.com/manual/Building.html

Build succeeded, but run failed because alsa is not installed:
```
~/Rack$ make run
...
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

MidiInAlsa::initialize: error creating ALSA sequencer client object.

terminate called after throwing an instance of 'RtMidiError'
  what():  MidiInAlsa::initialize: error creating ALSA sequencer client object.
```

Attempting to install alsa directly failed:
```
$ sudo apt-get install alsa
...
Package alsa is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'alsa' has no installation candidate
```

**Comment by grufwub** [comment]
I'm sorry to hear you're having this error! I ran a quick build myself just to confirm and I also ran into the same issue. Based on the error, this isn't due to a lack of Alsa, but Windows not exposing hardware to Windows Subsystem Linux. You can see people have had a similar issue here: https://github.com/Microsoft/WSL/issues/237

There's a user voice entry requesting support here: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14017329-sound-card-support
