### ISSUE TITLE
apt.patrickwu.space not resolving

### ISSUE THREAD

**Issue by PeteSL** [WhitewaterFoundry/Pengwin#466]
After the last Windows Store update, apt-get update indicates apt.patrickwu.space is not resolving.  Sure enough, it is not resolving.  Alternate fqdn for this repository?

**Comment by Biswa96** [comment]
I tested the new version. There is no `apt.patrickwu.space` URL in `/etc/apt/sources.list` or `/etc/apt/sources.list.d/whitewaterfoundry.list` file. Try to add a DNS like this `echo nameserver 1.1.1.1 > /etc/resolv.conf`.

**Comment by PeteSL** [comment]
Here is my /etc/apt/sources.list which does contain it (so maybe never removed on update?);
`# cat /etc/apt/sources.list
deb https://deb.debian.org/debian testing main contrib non-free
# deb-src https://deb.debian.org/debian testing main

deb https://deb.debian.org/debian testing-updates main
# deb-src https://deb.debian.org/debian testing-updates main

deb https://deb.debian.org/debian-security testing/updates main
# deb-src https://deb.debian.org/debian-security testing/updates main

deb https://deb.debian.org/debian/ unstable main contrib non-free
# deb-src https://deb.debian.org/debian/ unstable main contrib non-free

deb https://apt.patrickwu.space/ stable main
# obtain source from https://github.com/wslutilities/wslu`
Should I just comment it out?

**Comment by patrick330602** [comment]
Can you check the file `/etc/apt/sources.list.d/whitewaterfoundry.list`? if this file doesn't exist, you should update to the latest version of pengwin; otherwise, the line can be removed; it is notified to be removed after one month of pengwin release.

**Comment by PeteSL** [comment]
I have commented out the line.  No, that file does not exist yet the pengwin app is the latest release according to my Microsoft Store.  My installation dates back to WLinux and has been kept up-to-date via the store and apt-get on almost a daily basis.  The files in that directory are:
azurecli.list, stretch-backports.list, microsoft.list, and vscode.list.  All are dated Jan 15.  Thank you for your help.

**Comment by Kounavi** [comment]
I have the same issue. I have had this installed way back since WLinux.
Today, I also now get errors such as:

404  Not Found [IP: 54.230.202.147 443]
<other update info here>
Reading package lists... Done
E: The repository 'https://deb.debian.org/debian testing/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

This appeared after I got "apt update" notifications:
E: Repository 'https://cdn-aws.deb.debian.org/debian testing-updates InRelease' changed its 'Codename' value from 'buster-updates' to 'bullseye-updates'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N] 

and

E: Repository 'https://cdn-aws.deb.debian.org/debian testing-updates InRelease' changed its 'Codename' value from 'buster-updates' to 'bullseye-updates'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]

Any ideas?
