### ISSUE TITLE
Question about Pengwin, VMs, WSL1 and WSL2

### ISSUE THREAD

**Issue by N6REJ** [WhitewaterFoundry/Pengwin#481]
I'm a bit confused.. in your blog you state to run wsl2

> Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform

This implies pengwin is a vm not wsl kernel like ubuntu is?

Is this true of wsl 1? 
If it is wsl native(?) like ubuntu is, then how do you install it?
Thanks in advance.

**Comment by WSLUser** [comment]
PengWin is a distro like any other you install via the Store or build from Source. In order to use it, you need to enable WSL. WSL1, which is the original, utilizes the NT kernel. Due to this, there were bottlenecks in the I/O throughput. WSL2 attempts to alleviate this by utilizing a full Linux kernel which the WSL dev are optimizing. It was recently released in Insiders to play with after having demo'd it a few times already starting from MS Build. As Pengwin strives to make it easy for developers to install, instructions for enabling WSL are included. Since there are some scenarios that appear to work better in WSL2 at first glance (see the Phoronix perf blog), steps for enabling that are included. In order for WSL2 to utilize a Linux kernel, it needed to run in a VM, however unlike traditional VMs, this works almost at a container level, which the NT kernel itself we discovered has been doing for at least one or 2 releases. I highly suggest looking at the WSL blogs/docs to get more info. 

> This implies pengwin is a vm not wsl kernel like ubuntu is?

Pengwin and Ubuntu are one and the same in this sense. They only utilize the underlying structure, regardless of which version of WSL is running. Everything is user space. Pengwin offers some benefits over Ubuntu in that it provides a setup script to quickly and conveniently install most of the tools you'd need for your dev workflow and provides more dedicated support for WSL related issues. Ubuntu provides bare minimum support for WSL users. They support Hyper-V more than WSL from what I've seen (mostly because there aren't any Ubuntu specific errors that pertain only to Hyper-V unlike WSL).

**Comment by WSLUser** [comment]
@sirredbeard I just thought it might be a good idea to pin this issue to the top of the issue page.
