### ISSUE TITLE
apt update fails to find testing/updates 

### ISSUE THREAD

**Issue by pnelsonsr** [WhitewaterFoundry/Pengwin#488]
When I run 'apt update' it is not finding the debian-security testing/updates Release.

1. Go to the command line
2. Run apt update

apt update
Hit:1 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian buster InRelease
Hit:2 https://cdn-aws.deb.debian.org/debian testing InRelease
Hit:6 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian buster InRelease
Hit:7 https://packagecloud.io/whitewaterfoundry/wslu/debian buster InRelease
Hit:3 https://cdn-aws.deb.debian.org/debian testing-updates InRelease
Ign:4 https://cdn-aws.deb.debian.org/debian-security testing/updates InRelease
Hit:5 https://cdn-aws.deb.debian.org/debian unstable InRelease
Err:8 https://cdn-aws.deb.debian.org/debian-security testing/updates Release
  404  Not Found [IP: 13.224.29.41 443]
Reading package lists... Done
E: The repository 'https://deb.debian.org/debian-security testing/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Pengwin Version:  1.2.5.0

Windows Build:  10.0.18362 N/A Build 18362

If I comment out the line in sources.list then everything works.  I would prefer not resetting everything as this is used by me a lot.

**Comment by crramirez** [comment]
Hello,

Just run pengwin-setup and let it update. The run it again. It will patch your configuration. 

Regards

**Comment by ThatWeirdAndrew** [comment]
This seems to be a temporary side effect due to debian buster's transition from testing to stable and the unstable branch transitions to testing. A mailing list has stated that the *-updates repo is changing to *-security and the debian-security line in your sources.list file should be changed to `deb http://security.debian.org/debian-security testing-security main contrib non-free`

There is more info here:

https://www.reddit.com/r/debian/comments/ca2fvn/debian_testing_fails_to_upgrade_now/et5k3yd?utm_source=share&utm_medium=web2x

https://unix.stackexchange.com/a/528759/357954

**Comment by ThatWeirdAndrew** [comment]
Never mind, @crramirez's answer solves it.

**Comment by aaronvan** [comment]
> 
> 
> Hello,
> 
> Just run pengwin-setup and let it update. Then run it again. It will patch your configuration.
> 
> Regards

That works! Thanks.

**Comment by pnelsonsr** [comment]
@crramirez -> I ran pengwin-setup on pengwin cli and now my apt update (and ultimately then apt upgrade) works as it should.  Thanks for the heads up!
