### ISSUE TITLE
remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

### ISSUE THREAD

**Issue by eliranwong** [WhitewaterFoundry/Pengwin#556]
**Describe the bug**
I got this message with running several Linux apps in pengwin:
remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

**To Reproduce**
when I run:
> emacs

outup:
> (emacs:14321): GVFS-RemoteVolumeMonitor-WARNING **: 10:28:18.504: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

when I run:
> thunar

output
> (thunar:14615): GVFS-RemoteVolumeMonitor-WARNING **: 10:31:57.517: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

[Remarks: apps running in WSL2]

**Expected behavior**
It looks like the apps function as expected, but I wonder if I can address the issue underlying the message?

**Comment by Hemzyy** [comment]
Hello, have you found a solution for this problem?

**Comment by thewoz** [comment]
I have the same issue

**Comment by aceqbaceq** [comment]
I used to the error 
`invoking IsSupported() failed for remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor:: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown:`

the solution:
$ systemctl --user restart gvfs-udisks2-volume-monitor.service

**Comment by LouisThygesen** [comment]
@aceqbaceq's solution worked for me as well:

> $ systemctl --user restart gvfs-udisks2-volume-monitor.service

**Comment by fluffoid** [comment]
When running a pinned x11 installation with amber rendering installed it still does a system dump for all sorts of things. Although "systemctl --user restart gvfs-udisks2-volume-monitor.service" works rather well. Hardware acceleration is an iffy thing and there seems to be a good workaround for that as well. Even rendering pdfs can glitch suspiciously. The volume monitor dependencies cut cross-path with other apps and their frameworks, which I found terribly annoying and distracting. Rather than wasting countless hours explaining, I will sit back and peacefully enjoy a pensioners cup of tea. Also no need to sudo everything to death to acquiesce error messages that are essentially nothing more than overhyped warnings.

Quick get-it-working workarounds (bypass OpenGL)
mpv (pure X11 blit, no GL/VAAPI)
bash
mpv --vo=x11 --hwdec=no /path/to/video.mp4
If that works, make it permanent:
bash
mkdir -p ~/.config/mpv
printf "vo=x11\nhwdec=no\n" > ~/.config/mpv/mpv.conf
VLC (X11 output, software decode, software Qt)
bash
QT_OPENGL=software vlc --vout xcb_x11 --avcodec-hw=none /path/to/video.mp4

NOTE: Not everyone is wealthy enough to own a Nvidia hyped up computer on steroids (smile)
