### ISSUE TITLE
pengwin terminal window does not display unicode

### ISSUE THREAD

**Issue by eliranwong** [WhitewaterFoundry/Pengwin#562]
**Describe the bug**
pengwin terminal window does not display Chinese, Greek and Hebrew unicode characters at the same time.

**To Reproduce**
1) create a text containing Chinese, Greek and Hebrew characters
2) display the text on pengwin terminal
3) please see screenshot below, pengwin terminal on the left fails to display.  the terminal on the right is gnome-terminal.

**Screenshots**

https://github.com/eliranwong/wsl2/blob/master/terminal/screenshot_compare_terminals.png

**Comment by patrick330602** [comment]
Hi, thank you for the report. But I am afraid this is the bug more related to Windows Console itself as the font is controlled by it. I personally have this problem and have to change to the font to solve the problem. This bug is around for some time and as Microsoft is focusing on Windows Terminal with a new console backend, this bug will possibly be fixed in the next big release. Hope this answers your report.

I use [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) for Chinese and Japanese display

**Comment by eliranwong** [comment]
@patrick330602 

thanks for answer.  it is helpful, much appreciated.  I now understand it is an upstream issue.

I know I can change the font for the console.  In my case, however, changing font for the console is not enough, because I yet to find a font that can display Hebrew and Chinese at the same time.

My workaround is to install and use gnome-terminal or urxvt.
