### ISSUE TITLE
Thunar does not launch, "The connection is closed" error

### ISSUE THREAD

**Issue by ptmkenny** [WhitewaterFoundry/Pengwin#611]
**Describe the bug**
I installed Xfce4 and cannot launch Thunar.

**To Reproduce**
1. Install Pengwin, gui with Vcxsrv.
2. Install xfce4 with icons for Thunar: `sudo apt-install xfce4 xfce4-terminal gnome-icon-theme `
3. `startxfce4`
4. Click File Manager or Applications -> System -> Thunar.

**Expected behavior**
Thunar opens.

**What happens**
I get a "The connection is closed" error in the terminal.  I can use Firefox and such from Xfce fine.

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[ ] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

**Windows Build**

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. P7.30, 11/28/2016

**Comment by crramirez** [comment]
Hello,

Thanks for reporting. Could you confirm if you are using  WSL 1 or WSL 2?

Regards,
Carlos

**Comment by ptmkenny** [comment]
WSL 2

**Comment by crramirez** [comment]
Well, the problem is complex.

Xfce is not using the DBUS environment variables defined at startup. We will continue investigating in order to solve the issue. For now here are a couple of workarounds:

1. You can still run thunar from another session of pengwin or from the Windows start menu. For the start menu tell pengwin-setup to generate the start menu shortcuts: pengwin-setup->GUI->STARTMENU. Then start thunar:
![image](https://user-images.githubusercontent.com/8397379/83700703-cea31e80-a607-11ea-984a-f15e563e1e8c.png)

1. Modify the shortcut in Xfce to call the dbus configuration:
![image](https://user-images.githubusercontent.com/8397379/83700790-13c75080-a608-11ea-90c2-dcc72d7d6f9d.png)


Hope it helps

**Comment by ptmkenny** [comment]
Ok, thanks! I tried this in Ubuntu 20.04 by installing the xubuntu-desktop package collection and it worked out of the box, so maybe whatever solution Ubuntu applies can be used here too. (I'm not sure about this; just noting it in case it's helpful.)

**Comment by crramirez** [comment]
Hello,

Try this:

```language=bash
sudo rm /etc/dbus-1/session.conf
    sudo sed -i 's$<listen>.*</listen>$<listen>unix:tmpdir=/tmp</listen>$' /usr/share/dbus-1/session.conf
    sudo sed -i 's$<auth>ANONYMOUS</auth>$<auth>EXTERNAL</auth>$' /usr/share/dbus-1/session.conf
    sudo sed -i 's$<allow_anonymous/></busconfig>$</busconfig>$' /usr/share/dbus-1/session.conf
```

Try this and tell me if it improves
