### ISSUE TITLE
Windows Manager installation on WLinux

### ISSUE THREAD

**Issue by marcorotondi** [WhitewaterFoundry/Pengwin#781]
**Describe the bug**
After installed Jetbrains Intellij 2023.3.2 this option was disabled:

![image](https://github.com/WhitewaterFoundry/Pengwin/assets/22365419/58fd6cd7-5916-4c08-a032-915fe80cfef8)

**To Reproduce**
WLinux with latest update using X410dev and this installation

![image](https://github.com/WhitewaterFoundry/Pengwin/assets/22365419/6558d016-343c-4210-948c-2970a9a51bce)

**Expected behavior**
  Installed compatible window manager

Insert here:

Release Install Date: Mon Feb 20 10:24:40 CET 2023
Branch: ni_release
Build: 22631
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 1
Locale (Windows): it_IT
Theme (Windows): dark
Uptime (Windows): 0d 2h 28m
Version (WSL): 2
Uptime (WSL): 0d 0h 38m
Release: Pengwin
Kernel: Linux 5.15.133.1-microsoft-standard-WSL2
Packages: 938
IPv4 Address: 172.19.155.110
System Type (Windows): Desktop
SystemD Status: enabled

**Comment by crramirez** [comment]
Hello,

Probably it is because what is described here: https://x410.dev/news/jetbrains-resurrects-the-title-bar-in-its-new-ui-for-wsl-users-here-is-a-workaround-to-remove-it/

Intellij detects that is running inside WSL and modifies itself it's behavior.

Try unsetting WSL_DISTRO_NAME to avoid Intellij detect that is running inside WSL:

`unset WSL_DISTRO_NAME`

Regards

**Comment by marcorotondi** [comment]
Please close this issue I fix it add on my env:

XDG_CURRENT_DESKTOP=X410 and remove WSL_DISTRO_NAME
